[build]
  command = "npm run build"
  functions = "dist/api"
[template.environment]
  CONTENTFUL_SPACE_ID = "Contentful Space ID"
  CONTENTFUL_TOKEN = "Contentful Content Delivery API - access token "
  CONTENTFUL_ENVIRONMENT = "Environment like master"
  AUTH_SECRET="Your auth secret"
  AUTH_USER_LIST="Auth username split by comma"
  AUTH_ISSUER="Issuer ID"
  AUTH_AUDIENCE="Client ID"
  GENERATE_SOURCEMAP=false